typography_spectrum: 0.5186109121423215
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.4910640665329993
  lightness: 0.9247184908017516
  saturation: 0.7129183614160866
  rhythmicContrast: 0.9474944693502039
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.45327016431838274
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Pasi Lepola
  email: pasi.lepola@gmail.com
  url: www.pasilepola.fi
name: Fyysikon silmin
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Fyysikon silmin
purpose: []
