typography_spectrum: 0.017382225953042507
color:
  brandColors:
    - '#36362C'
    - '#5D917D'
    - '#A8AD80'
    - '#E6D4A7'
    - '#825534'
  brandStrength: 0.4243161561898887
  lightness: 0.15446846606209874
  saturation: 0.11566842650063336
  rhythmicContrast: 0.42152833309955895
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24431576975621283
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Pasi Lepola
  email: pasi.lepola@gmail.com
  url: www.pasilepola.fi
name: Fyysikon silmin
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Fyysikon silmin
description: Välähdyksiä lääketieteellisen fysiikan maailmasta
purpose: []
