typography_spectrum: 0.58265
color:
  brandColors:
    - '#7f7f7f'
    - '#000000'
    - '#ffffff'
    - '#373737'
    - '#b7b7b7'
  brandStrength: 0.3849882357753813
  lightness: 0.18972346116788685
  saturation: 0.6227402286604047
  rhythmicContrast: 0.8099141691345721
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Pasi Lepola
  email: pasi.lepola@gmail.com
  url: www.pasilepola.fi
name: Fyysikon silmin
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Fyysikon silmin
purpose: []
