name: Fyysikon silmin
favicon: null
layout_spectrum: 0.83504
typography_spectrum: 0.050436916295439005
title: Fyysikon silmin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7f7f7f'
    - '#000000'
    - '#ffffff'
    - '#373737'
    - '#b7b7b7'
  brandStrength: 0.3849882357753813
  lightness: 0.18972346116788685
  saturation: 0.6227402286604047
  rhythmicContrast: 0.8099141691345721
purpose: []
